### ISSUE TITLE
[ondemandkorea] 0.5.6: Opening next page not possible

### ISSUE THREAD

**Issue by kodan2k** [xbmc-korean-tv/addons#10]
When you open a directory with more than 20 entries it is not possible to access the next page. When you select "Next page" the same content is shown again.
[kodi.log](https://github.com/xbmc-korean-tv/addons/files/3101114/kodi.log)

**Comment by kodan2k** [comment]
no change with 0.5.6

**Comment by xornidian** [comment]
no change with 0.5.7 at least for me

**Comment by xalagaco** [comment]
This has been fixed since 0.6.0. Please close.
